Mod = {'Noise': '0.Noise',
       'OOK': '1.ASK',
       '4ASK': '1.ASK',
       '8ASK': '1.ASK',
       'BPSK': '2.PSK',
       'QPSK': '2.PSK',
       'OQPSK': '2.PSK',
       '8PSK': '2.PSK',
       '16PSK': '2.PSK',
       '32PSK': '2.PSK',
       '16QAM': '3.QAM',
       '32QAM': '3.QAM',
       '64QAM': '3.QAM',
       '16APSK': '4.APSK',
       '32APSK': '4.APSK',
       '64APSK': '4.APSK',
       '128APSK': '4.APSK',
       '128QAM': '3.QAM',
       '256QAM': '3.QAM',
       'AM-SSB-WC': '5.AM',
       'AM-SSB-SC': '5.AM',
       'AM-DSB-WC': '5.AM',
       'AM-DSB-SC': '5.AM',
       'FM': '6.FM',
       'GMSK': '7.GMSK'}

